config/urls.py
from django.contrib import admin
from django.urls import path, include
from vehiculo.views import indexView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', indexView, name= 'index'),
    path('vehiculo/', include('vehiculo.urls')),
]

vehiculo/models.py
from django.db import models

# Create your models here.
#Creación de Modelo Vehiculo (Drilling Final, parte 1)
#Definicón de lista de opciones de marca
vehiculo_marca = [
    ('Fiat', 'Fiat'),
    ('Chevrolet', 'Chevrolet'),
    ('Ford', 'Ford'),
    ('Toyota', 'Toyota')
]
#Definicón de lista de opciones de categoria
vehiculo_categoria = [
    ('Particular', 'Particular'),
    ('Transporte', 'Transporte'),
    ('Carga', 'Carga')
    ]

class VehiculoModel(models.Model):
    marca = models.CharField(max_length=20, null=False, blank=False,
                                choices=vehiculo_marca, default= 'Ford')
    modelo = models.CharField(max_length=100)
    serial_carroceria = models.CharField(max_length=50)
    serial_motor = models.CharField(max_length=50)
    categoria = models.CharField(max_length=20, null=False, blank=False,
                                choices=vehiculo_categoria, default= 'Particular')
    precio = models.IntegerField()
    creado= models.DateTimeField(auto_now_add=True)
    modificado= models.DateTimeField(auto_now=True)
    
    #Se crea Class Meta para creación de permisos(Drilling Final, parte 4)
    class Meta:
              
        permissions = (
            ("visualizar_catalogo", "Puede visualizar catálogo vehículo"),
           
        )
    
    def __str__(self):
        return self.marca

templates/add.html
<!--Creación de add.html, usando models.py(Drilling Final, parte 2)-->
<!--Se agrega herencia plantilla base.html-->

{% extends 'base.html' %}

{% block content %}
{% load crispy_forms_tags %}
<div class="container py-5" id="vehiculo-add"> 
    
    <div>
        <h1>Agregar Vehículo</h1>
    </div>
    <form acction="" method="POST" id="form-add">
            {% csrf_token %}
            {{form | crispy }}
        <div class="d-flex justify-content" >
            <button type="submit" id="btn-submit" class="btn btn-warning ">Enviar</button>
        </div>
    </form>
            
</div> 
{% endblock  %}

templates/base.html
<!--Creación de base.html, con la estructura básica de "HTML"-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <!--Título de Página-->
    <title>VENTA VIRTUAL DE VEHÍCULOS</title>
    <!--Fontawesome-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384- UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <!--Fuente-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <!--CSS-->
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <!--Bootstrap 5-->
    {% load bootstrap5 %}
    <!--Bootstrap CSS-->
    {% bootstrap_css %}  
    <!--Bootstrap JSS-->   
    {% bootstrap_javascript %}
    <!--Bootstrap Messages-->
    {% bootstrap_messages %}
    <!--Icon-->
    <link rel="icon" type="image/svg+xml" href="{% static 'img/logdrilling.ico' %}">
</head>
<body id="body">

    <header>
    {% block nav %}
    {% include 'navbar.html' %}
    {% endblock nav %}
    </header>
    <main class="container">
    {% block content %}
    {% endblock content %}
    </main>
    <footer>
        <div id="footer">
            <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4  mb-0" style="background-color:#323339;">
              <div class="col-md-4 d-flex align-items-center">
                <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
                    <img src="{% static 'img/logdrilling.png' %}" alt="" width="80" height="60">
                </a>
                <span class="mb-3 mb-md-0 text-muted">Drilling Final, Módulo 6 | Venta Virtual de Vehículos</span>
              </div>
          
              <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
                <li class="ms-3"><a class="text-muted" href="https://www.fiat.cl/" target="black"><img class="bi" src="{% static 'img/fiat.png' %}" width="44" height="50"></a></li>
                <li class="ms-3"><a class="text-muted" href="https://www.chevrolet.cl/" target="black"><img class="bi" src="{% static 'img/chevrolet.png' %}" width="50" height="40"></a></li>
                <li class="ms-3"><a class="text-muted" href="https://www.ford.cl/" target="black"><img class="bi" src="{% static 'img/ford.png' %}" width="50" height="44"></a></li>
                <li class="ms-3"><a class="text-muted" href="https://toyota.cl" target="black"><img class="bi" src="{% static 'img/toyota.png' %}" width="50" height="44"></a></li>
              </ul>
            </footer>
          </div>
    </footer>
<!--JQuery-->
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<!--JavaScript-->
<script src="{% static 'js/main.js' %}"></script>
{% block javascripts%}
{% endblock javascripts%}
</body>
</html>

templates/galeria.html
<!--Creación de lista.html (Drilling Final, Extras)-->
<!--Se agrega herencia plantilla base.html-->

<!--Para la información de las Cards-->
<!--Se genera un ciclo for para obtener datos de la db-->
<!--Se genera condicional para obtener datos filtrando por marca a exepción de la marca
    Fiat que tiene dos modelos, en ese caso se filtra por modelo-->

{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="galeria">
    <div class="seleccion py-3 mb-5" id="seleccion">
        <div class="galeria-principal" style="width: 25rem">
            <div class="card fondo py-2 " style="width: 25rem">
                     <img src="{% static 'img/ford-f150.png' %}" alt="" class="img-principal" id="img">
                    {% for lista in listas %}
                        {% if lista.marca == 'Ford' %}
                    <div class="card-body parrafo-small">
                        <h2 class="card-title" id="marca"><small class="text-mute">marca:</small> {{ lista.marca }}</h2>
                        <h3 class="card-title" id="modelo"><small class="text-mute">modelo:</small> {{ lista.modelo }}</h3>
                        <h4 class="card-title" id="precio"><small class="text-mute">precio:</small> ${{ lista.precio }}</h4>
                    </div>  
                        {% endif %}  
                    {% endfor %} 
                
            </div>
        </div>
    </div>
    <div class="mostrador" id="mostrador">
        <div class="row galeria-escaparate ">
            <div class="item col" onclick="mostrar(this)">
                <div class="card mx-4 mb-5 h-60 card-item" style="width: 5rem;">
                     <img src="{% static 'img/fiat-punto.png' %}" class="card-img-top" alt="imagen-1">
                    {% for lista in listas %}
                        {% if lista.modelo == 'Punto' %}
                    <div class="card-body gal-pa">
                        <h2 class="card-title marca"><small>marca:</small> {{ lista.marca }}</h2>
                        <h3 class="card-title modelo"><small>modelo:</small> {{ lista.modelo}}</h3>
                        <h4 class="card-title precio"><small>precio:</small> ${{ lista.precio }}</h4>
                    </div>
                        {% endif %}  
                    {% endfor %}
                </div>
            </div>
            <div class="item col" onclick="mostrar(this)">
                <div class="card mx-4 mb-5 h-60 card-item" style="width: 5rem;">
                    <img src="{% static 'img/fiat-ducato.png' %}" class="card-img-top" alt="imagen-2">
                    {% for lista in listas %}
                        {% if lista.modelo == 'Furgoneta Ducato' %}
                    <div class="card-body gal-pa">
                        <h2 class="card-title marca"><small>marca:</small> {{ lista.marca }}</h2>
                        <h3 class="card-title modelo"><small>modelo:</small> {{ lista.modelo }}</h3>
                        <h4 class="card-title precio"><small>precio:</small> ${{ lista.precio }}</h4>
                    </div>
                        {% endif %}  
                    {% endfor %}
                </div>               
            </div>
            <div class="item col" onclick="mostrar(this)">
                <div class="card mx-4 mb-5 h-60 card-item acitve" style="width: 5rem;">
                    <img src="{% static 'img/ford-f150.png' %}" class="card-img-top" alt="imagen-0">
                    {% for lista in listas %}
                        {% if lista.marca == 'Ford' %}
                    <div class="card-body gal-pa">
                        <h2 class="card-title marca"><small>marca:</small> {{ lista.marca }}</h2>
                        <h3 class="card-title modelo"><small>modelo:</small> {{ lista.modelo }}</h3>
                        <h4 class="card-title precio"><small>precio:</small> ${{ lista.precio }}</h4>
                     </div> 
                     {% endif %}  
                    {% endfor %}     
                </div>
            </div>
            <div class="item col" onclick="mostrar(this)">
                <div class="card mx-4 mb-5 h-60 card-item" style="width: 5rem;">
                    <img src="{% static 'img/toyota-4runner.png' %}" class="card-img-top" alt="imagen-3">
                    {% for lista in listas %}
                        {% if lista.marca == 'Toyota' %}
                    <div class="card-body gal-pa">
                        <h2 class="card-title marca"><small>marca:</small> {{ lista.marca }}</h2>
                        <h3 class="card-title modelo"><small>modelo:</small> {{ lista.modelo }}</h3>
                        <h4 class="card-title precio"><small>precio:</small> ${{ lista.precio }}</h4>
                    </div>
                        {% endif %}  
                    {% endfor %}
                </div>                
            </div>
            <div class="item col" onclick="mostrar(this)">
                <div class="card mx-4 mb-5 h-60 card-item" style="width: 5rem;">
                    <img src="{% static 'img/chevrolet-corvette.png' %}" class="card-img-top" alt="imagen-4">
                    {% for lista in listas %}
                        {% if lista.marca == 'Chevrolet' %}
                    <div class="card-body gal-pa">
                        <h2 class="card-title marca"><small>marca:</small> {{ lista.marca }}</h2>
                        <h3 class="card-title modelo"><small>modelo:</small> {{ lista.modelo }}</h3>
                        <h4 class="card-title precio"><small>precio:</small> ${{ lista.precio }}</h4>
                    </div>
                        {% endif %}  
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>   
    
{% endblock  %}

{% block javascripts%}
<script type="text/javascript">
    let mostrador = document.getElementById("mostrador");
    let seleccion = document.getElementById("seleccion");
    let selectImg = document.getElementById("img");
    let selectMarca = document.getElementById("marca");
    let selectModelo = document.getElementById("modelo");
    let selectPrecio = document.getElementById("precio");
    
    function mostrar(item){
        eliminarBordes();
               
        selectImg.src = item.getElementsByTagName("img")[0].src;
    
        selectMarca.innerHTML =  item.getElementsByTagName("h2")[0].innerHTML;
    
        selectModelo.innerHTML = item.getElementsByTagName("h3")[0].innerHTML;
    
        selectPrecio.innerHTML =  item.getElementsByTagName("h4")[0].innerHTML;
    
    }

    function eliminarBordes(){
        var items = document.getElementsByClassName("item");
        for(i=0;i <items.length; i++){
            items[i].style.border = "none";
        }
    }
</script>
{% endblock javascripts%}

templates/index.html
<!--Creación de Index.html, (Drilling Final, parte 2)-->
<!--Se agrega herencia plantilla base.html-->

{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container py-5 fh">       
        <h1 id="index">Cátalogo de Vehículos</h1> 
    </div>
   
{% endblock %}

templates/lista.html
<!--Creación de lista.html (Drilling Final, parte 4)-->
<!--Se agrega herencia plantilla base.html-->

{% extends 'base.html' %}
{% load static %}
{% block content %}
<div  class="container py-5" id="vehiculo-list">
    <div class="list-v py-3">
      <h1>Listado de Vehículos</h1>
    </div>
  <div class="card" id="card-list"> 
      <table class="table table-hover text-center table-responsive-sm" >
      <thead>
        <tr id="list-tabla">
          <th>MARCA</th>
          <th>MODELO</th>
          <th>SERIAL CARROCERIA</th>
          <th>SERIAL MOTOR</th>
          <th>CATEGORIA</th>
          <th>PRECIO</th>
          <th>CONDICION DE PRECIOS</th>
         </tr>
      </thead>
     {% if listas %}
     {% for lista in listas %}
      <tbody>
        <tr>
          <th>{{lista.marca}}</th>
          <td>{{lista.modelo}}</td>
          <td>{{lista.serial_carroceria}}</td>
          <td>{{lista.serial_motor}}</td>
          <td>{{lista.categoria}}</td>
          <td>${{lista.precio}}.-</td>
          <td> 
            <!--Se usa condicional para obtener Condición de Precios-->
            {% if lista.precio > 30000 %}
                Alto
            {% elif lista.precio > 10000 and lista.precio <= 30000 %}
               Medio
            {% elif lista.precio <= 10000 %}
               Bajo
            {% else %}
                Oops, algo anda mal!
            {% endif%}              
          </td>
          <!--Se agrega button "Modificar"(Drilling Final, Extras)-->
          <!--Se condiona según usuario la opción de botton modificar en la url list.html-->
          {% if perms.vehiculo.add_vehiculomodel %}
          <td><button type="button" class="btn btn-warning" onclick="abrir_modal_modificar('{% url 'modal' lista.id%}')" data-bs-toggle="modal" data-bs-target="#exampleModal">Modificar</button>
          </td>
          {% endif%}
        </tr>
      </tbody>
      {% endfor%}
      {% else %}
      <h1>No existe lista</h1>
      {% endif %}
   </table>
  </div>
  <div class="modal fade" id="modificar" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  </div> 
</div> 
{% endblock  %}
<!--Se agrega código javascripts para el funcinamiento de Modal-->
{% block javascripts%}
<script type="text/javascript">
  function abrir_modal_modificar(url){
    $('#modificar').load(url, function(){
      $(this).modal('show');
    });
  }
</script>
{% endblock javascripts%}

templates/login.html
<!--Se crea login.html (Drilling Final, parte 4)-->
{% extends 'base.html' %}
{% block content %} 
    {% load crispy_forms_tags %}

<!--Login-->
  <div class="container py-5" id="vehiculo-login">
     <h1>Login</h1>
      <form method="POST">
         {% csrf_token %} 
         {{ login_form|crispy }} 
         <button class="btn btn-warning" type="submit" id="btn-submit">Login</button> 
      </form> 
      <p class="text-center py-5" id="p-login"> 
        Si no tienes una cuenta, registrate en 
        <a href="{% url 'registro' %}">Registro</a>, para crear una cuenta
      </p>
  </div> 

{% endblock %}

templates/modal.html
<!--Se crea modal.html para la button modificar(Drilling Final, Extras)-->
{% load bootstrap5 %}
{% bootstrap_css %} 
{% bootstrap_javascript %}
{% bootstrap_messages %}
{% load static %}
{% load crispy_forms_tags %}


<div class="modal-dialog bg-light">        
  <div class="modal-content">
      <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modificar Vehículo</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
  <form action="" method="POST">
      <div class="modal-body">
          {% csrf_token %}
          {{form | crispy }}          
      </div>
      <div class="modal-footer">
          <div>
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
              <button type="submit" class="btn btn-warning" >Confirmar</button>
          </div>
      </div> 
  </form>
  </div>
</div>  
   

templates/navbar.html
<!--Se crea navbar.html(Drilling Final, parte 3)-->
{% load bootstrap5 %}
{% bootstrap_css %}     
{% bootstrap_javascript %}
{% load static %}
{% block nav %}
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color:#323339;">
    <div class="container-fluid">
      <a class="navbar-brand" href=""><img src="{% static 'img/logdrilling.png' %}" alt="" width="80" height="60"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Inicio</a>
          </li>
          <!--Se condiona según usuario la opción de ver y agregar en la url add.html-->
          {% if perms.vehiculo.add_vehiculomodel %}
          <li class="nav-item"> 
            <a class="nav-link" href="{% url 'add' %}">Agregar</a>
          </li>
          {% endif%}
          <!--El usuario debe estar registrado para ver list.html-->
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'list' %}">Listar</a>
          </li>
          
          <!--Se condiona según usuario la opción de ver la url galeria.html-->
          {% if perms.vehiculo.add_vehiculomodel %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'galeria' %}">Galeria</a>
          </li>
          {% endif%}
        </ul>
       
      </div>
    </div>
   
    <!--Se añade al navbar Autentificación del Usuario-->
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Salir</a>
          </li> 
          <li class="nav-item">
            <a class="nav-link" href="#"><span style="color: #F5FFCB;">Hola, <em>{{user.username | capfirst}}</em></span></a>
          </li>  
        {% else %}
          <li class="nav-item">
           <a class="nav-link" href="{% url 'registro' %}">Registrar</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>
        {% endif %} 
      </ul>
    </div>
    <!--Fin autentificación usuario-->

  </nav>
  {% endblock %}
  

templates/registro.html
<!--Se crea registro.html (Drilling Final, parte 4)-->
{% extends 'base.html' %}
{% block content %} 
  {% load crispy_forms_tags %}

<!--Registro-->
  <div class="container py-5" id="vehiculo-registro">
      <h1>Registro</h1>
      <form method="POST">
         {% csrf_token %} 
         {{ register_form |crispy }} 
         <button class="btn btn-warning" type="submit" id="btn-submit">Registrar</button> 
      </form> 
      <p class="text-center" id="p-registro"> 
        Si tienes actualmente una cuenta, inicie su sesión en 
        <a href="{% url 'login' %}">Login</a>
      </p>
  </div> 

{% endblock %}